### ISSUE TITLE
Agent modle save

### ISSUE THREAD

**Issue by Q5mi1e** [notmahi/disk#1]
Hi.
First of all,thank you for great work and publishing the DISK code.
I have a rudimentary question:
How could i save the incremental_agent model?
I try this:

> class IncrementalAgent(Agent, **nn.Module**)
and
```
        torch.save(self.agent, "/home/admin641/disk-main/disk-main/Checkpoints/" + "/params.pth")
        print("Done training")
```
But i got the following error:
```
Traceback (most recent call last):
  File "/home/admin641/disk-main/disk-main/train.py", line 315, in main
    workspace.run()
  File "/home/admin641/disk-main/disk-main/train.py", line 215, in run
    torch.save(self.agent, "/home/admin641/disk-main/disk-main/Checkpoints/" + "/params.pth")
  File "/home/admin641/anaconda3/envs/disk/lib/python3.9/site-packages/torch/serialization.py", line 619, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "/home/admin641/anaconda3/envs/disk/lib/python3.9/site-packages/torch/serialization.py", line 831, in _save
    pickler.dump(obj)
RuntimeError: Tried to serialize object __torch__.agent.critic.DoubleQCritic which does not have a __getstate__ method defined!
```

**Comment by Q5mi1e** [comment]
Sorry to bother you, my problem is solved, what I did was to save the `agent.state_dict()`, and then save the `skill_actors` in the agent, so that I can use the trained skill_actors when loading the model, so I'll close this issue.
